# Generated by Django 4.1.1 on 2022-09-23 19:08

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('geoip', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('range_to'), '-', models.F('range_from')), name='tracker_ip_length'),
        ),
    ]
