default_language_version:
  python: python

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        args: ['--py3-plus', '--py310-plus', '--keep-percent-format']
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        exclude: /migrations/
        types: [python]
