default_language_version:
  python: python

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args:
          - --python-version=3.12
          - --no-strict-optional
          - --ignore-missing-imports
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --disallow-untyped-decorators
          - --check-untyped-defs
          - --strict-equality
        additional_dependencies:
          - types-Markdown
          - types-requests
          - types-pytz
          - types-python-dateutil
