# Generated by Django 4.1.7 on 2023-04-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_fill_profile_first_seen_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.server",
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="merged_into_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="merged_stats_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
