# Generated by Django 4.1.7 on 2023-08-10 11:11

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_server_merged_into_server_merged_into_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(
                help_text="TSV field for full text search.", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="search_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="alias_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                help_text="Denormalized list of alias names for search vector.",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="names_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                django.db.models.functions.text.Upper("country"),
                models.OrderBy(models.F("last_seen_at"), descending=True),
                models.F("id"),
                condition=models.Q(("last_seen_at__isnull", False)),
                name="tracker_profile_search_by_country_idx",
            ),
        ),
    ]
