# Generated by Django 4.1.7 on 2023-08-10 11:13

import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_profile_search_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(
                help_text="TSV field for full text search.", null=True
            ),
        ),
        migrations.AddField(
            model_name="alias",
            name="search_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="alias",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="alias",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
