# Generated by Django 2.2.16 on 2021-01-02 00:45
import apps.utils.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tracker', '0005_add_custom_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=apps.utils.db.fields.EnumField(db_column='gametype_enum', enum_type='gametype_enum', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=apps.utils.db.fields.EnumField(db_column='outcome_enum', enum_type='outcome_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='body',
            field=apps.utils.db.fields.EnumField(db_column='body_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='breacher',
            field=apps.utils.db.fields.EnumField(db_column='breacher_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='equip_five',
            field=apps.utils.db.fields.EnumField(db_column='equip_five_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='equip_four',
            field=apps.utils.db.fields.EnumField(db_column='equip_four_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='equip_one',
            field=apps.utils.db.fields.EnumField(db_column='equip_one_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='equip_three',
            field=apps.utils.db.fields.EnumField(db_column='equip_three_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='equip_two',
            field=apps.utils.db.fields.EnumField(db_column='equip_two_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='head',
            field=apps.utils.db.fields.EnumField(db_column='head_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='primary',
            field=apps.utils.db.fields.EnumField(db_column='primary_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='primary_ammo',
            field=apps.utils.db.fields.EnumField(db_column='primary_ammo_enum', enum_type='ammo_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='secondary',
            field=apps.utils.db.fields.EnumField(db_column='secondary_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AddField(
            model_name='loadout',
            name='secondary_ammo',
            field=apps.utils.db.fields.EnumField(db_column='secondary_ammo_enum', enum_type='ammo_enum', null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='name',
            field=apps.utils.db.fields.EnumField(db_column='name_enum', enum_type='objective_enum', null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='status',
            field=apps.utils.db.fields.EnumField(db_column='status_enum', enum_type='objective_status_enum', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='coop_status',
            field=apps.utils.db.fields.EnumField(db_column='coop_status_enum', enum_type='coop_status_enum', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=apps.utils.db.fields.EnumField(db_column='team_enum', enum_type='team_enum', null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=apps.utils.db.fields.EnumField(db_column='name_enum', enum_type='procedure_enum', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=apps.utils.db.fields.EnumField(db_column='team_enum', enum_type='team_enum', null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=apps.utils.db.fields.EnumField(db_column='name_enum', enum_type='equipment_enum', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Alias'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='loadout',
            unique_together={('primary', 'secondary', 'primary_ammo', 'secondary_ammo', 'equip_one', 'equip_two', 'equip_three', 'equip_four', 'equip_five', 'head', 'body', 'breacher')},
        ),
    ]
