# Generated by Django 4.1.7 on 2023-07-24 17:09

from django.contrib.postgres.search import SearchVectorField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alias_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="search",
            field=SearchVectorField(help_text="TSV field for full text search.", null=True),
        ),
    ]
