# Generated by Django 4.1.7 on 2023-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alias_created_at_alias_isp_country_alias_isp_name_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
            -- Trigger to set tracker_alias.profile_name during an insert on tracker_alias
            CREATE OR REPLACE FUNCTION insert_alias_set_profile_name()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.profile_name = (SELECT name FROM tracker_profile WHERE id = NEW.profile_id);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS insert_alias_set_profile_name ON tracker_alias;
            CREATE TRIGGER insert_alias_set_profile_name
            BEFORE INSERT ON tracker_alias
            FOR EACH ROW
            EXECUTE FUNCTION insert_alias_set_profile_name();
        """),
        migrations.RunSQL("""
            -- Trigger to update tracker_alias.profile_name after an update of referenced tracker_profile.name
            CREATE OR REPLACE FUNCTION update_profile_name_sync_to_alias_profile_name()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE tracker_alias
                SET profile_name = NEW.name
                WHERE profile_id = NEW.id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS update_profile_name_sync_to_alias_profile_name ON tracker_profile;
            CREATE TRIGGER update_profile_name_sync_to_alias_profile_name
            AFTER UPDATE OF name ON tracker_profile
            FOR EACH ROW
            EXECUTE FUNCTION update_profile_name_sync_to_alias_profile_name();
        """),
        migrations.RunSQL("""
            -- Trigger to update tracker_alias.profile_name after an update of tracker_alias.profile_id FK
            CREATE OR REPLACE FUNCTION update_alias_profile_fk_set_new_profile_name()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.profile_name = (SELECT name FROM tracker_profile WHERE id = NEW.profile_id);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS update_alias_profile_fk_set_new_profile_name ON tracker_alias;
            CREATE TRIGGER update_alias_profile_fk_set_new_profile_name
            BEFORE UPDATE OF profile_id ON tracker_alias
            FOR EACH ROW
            EXECUTE FUNCTION update_alias_profile_fk_set_new_profile_name();
        """),
        migrations.RunSQL("""
            -- Trigger to set tracker_alias.isp_name and tracker_alias.isp_country during an insert on tracker_alias
            CREATE OR REPLACE FUNCTION insert_alias_set_isp_name_country()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.isp_name = (SELECT name FROM tracker_isp WHERE id = NEW.isp_id);
                NEW.isp_country = (SELECT country FROM tracker_isp WHERE id = NEW.isp_id);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS insert_alias_set_isp_name_country ON tracker_alias;
            CREATE TRIGGER insert_alias_set_isp_name_country
            BEFORE INSERT ON tracker_alias
            FOR EACH ROW
            EXECUTE FUNCTION insert_alias_set_isp_name_country();
        """),
        migrations.RunSQL("""
            -- Trigger to update tracker_alias.isp_name and tracker_alias.isp_country an after update of either tracker_isp.name or tracker_isp.country
            CREATE OR REPLACE FUNCTION update_isp_name_country_sync_to_alias_isp_name_country()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE tracker_alias
                SET isp_name = NEW.name,
                    isp_country = NEW.country
                WHERE isp_id = NEW.id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS update_isp_name_country_sync_to_alias_isp_name_country ON tracker_isp;
            CREATE TRIGGER update_isp_name_country_sync_to_alias_isp_name_country
            AFTER UPDATE OF name, country ON tracker_isp
            FOR EACH ROW
            EXECUTE FUNCTION update_isp_name_country_sync_to_alias_isp_name_country();
        """),
        migrations.RunSQL("""
            -- Trigger to update tracker_alias.isp_name and tracker_alias.isp_country after an update of tracker_alias.isp_id FK
            CREATE OR REPLACE FUNCTION update_alias_isp_fk_set_new_isp_name_country()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.isp_name = (SELECT name FROM tracker_isp WHERE id = NEW.isp_id);
                NEW.isp_country = (SELECT country FROM tracker_isp WHERE id = NEW.isp_id);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS update_alias_isp_fk_set_new_isp_name_country ON tracker_alias;
            CREATE TRIGGER update_alias_isp_fk_set_new_isp_name_country
            BEFORE UPDATE OF isp_id ON tracker_alias
            FOR EACH ROW
            EXECUTE FUNCTION update_alias_isp_fk_set_new_isp_name_country();
        """)
    ]
