# Generated by Django 4.1.7 on 2023-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_add_profile_names"),
    ]

    operations = []
