# Generated by Django 4.1.7 on 2023-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_add_profile_names'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION insert_update_alias_update_profile_names()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE tracker_profile AS tp
                SET names = ARRAY(
                    SELECT DISTINCT name
                    FROM tracker_alias AS ta
                    WHERE profile_id = NEW.profile_id AND (tp.name IS NULL OR tp.name != ta.name)
                )
                WHERE tp.id = NEW.profile_id;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS insert_update_alias_update_profile_names ON tracker_alias;
            CREATE TRIGGER insert_update_alias_update_profile_names
            AFTER INSERT OR UPDATE OF "profile_id", "name" ON tracker_alias
            FOR EACH ROW EXECUTE FUNCTION insert_update_alias_update_profile_names();
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION delete_alias_update_profile_names()
            RETURNS TRIGGER AS $$
            BEGIN
                UPDATE tracker_profile AS tp
                SET names = ARRAY(
                    SELECT DISTINCT name
                    FROM tracker_alias AS ta
                    WHERE profile_id = OLD.profile_id AND (tp.name IS NULL OR tp.name != ta.name)
                )
                WHERE id = OLD.profile_id;
                RETURN OLD;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS delete_alias_update_profile_names ON tracker_alias;
            CREATE TRIGGER delete_alias_update_profile_names
            AFTER DELETE ON tracker_alias
            FOR EACH ROW EXECUTE FUNCTION delete_alias_update_profile_names();
        """)
    ]
