# Generated by Django 4.2.4 on 2023-09-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_map_first_game_map_first_game_played_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="rating_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
