# Generated by Django 5.1 on 2024-08-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_server_rating_server_rating_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="slug",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
