# Generated by Django 4.1.7 on 2023-07-25 09:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_denorm_profile_alias_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="search",
            field=django.contrib.postgres.search.SearchVectorField(
                help_text="TSV field for full text search.", null=True
            ),
        ),
    ]
