# Generated by Django 4.1.7 on 2023-07-25 09:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_denorm_profile_alias_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(help_text='TSV field for full text search. Updated by triggers.', null=True),
        ),
        migrations.RunSQL(r"""
            CREATE OR REPLACE FUNCTION update_or_create_profile_reindex_search()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.search :=
                    setweight(to_tsvector('simple', NEW.name), 'A')
                    || ' ' ||
                    setweight(to_tsvector('simple', array_to_string(NEW.names, ' ')), 'B')
                    || ' ' ||
                    setweight(
                        to_tsvector('simple',
                            regexp_replace(
                                regexp_replace(
                                    coalesce(NEW.name, '') || ' ' || array_to_string(NEW.names, ' '),
                                    '([a-z])([A-Z])', '\1 \2', 'g'
                                ),
                                '\d+', ''
                            )
                    ), 'C');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER update_or_create_profile_reindex_search
            BEFORE INSERT OR UPDATE OF name, names
            ON tracker_profile FOR EACH ROW EXECUTE FUNCTION update_or_create_profile_reindex_search();
        """),
    ]
