# Generated by Django 5.1 on 2024-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0010_map_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="background_picture",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="briefing",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="details_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="details_updated_for_version",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="preview_picture",
            field=models.TextField(null=True),
        ),
    ]
