# Generated by Django 5.1 on 2024-08-19 21:19

from django.db import migrations

import apps.utils.db.fields
from apps.utils.db.operations import CreateEnumType


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_map_background_picture_map_briefing_and_more"),
    ]

    operations = [
        CreateEnumType(
            "coop_rank_enum",
            [
                "Chief Inspector",
                "Inspector",
                "Captain",
                "Lieutenant",
                "Sergeant",
                "Patrol Officer",
                "Reserve Officer",
                "Non-sworn Officer",
                "Recruit",
                "Washout",
                "Vigilante",
                "Menace",
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="coop_rank",
            field=apps.utils.db.fields.EnumField(enum_type="coop_rank_enum", null=True),
        ),
    ]
