# Generated by Django 4.1.7 on 2023-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0011_profile_tracker_profile_search_by_country_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="alias_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="names_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="search_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS insert_update_alias_update_profile_names ON tracker_alias"
        ),
        migrations.RunSQL("DROP FUNCTION IF EXISTS insert_update_alias_update_profile_names"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS delete_alias_update_profile_names ON tracker_alias"
        ),
        migrations.RunSQL("DROP FUNCTION IF EXISTS delete_alias_update_profile_names"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS update_or_create_profile_reindex_search ON tracker_profile"
        ),
        migrations.RunSQL("DROP FUNCTION IF EXISTS update_or_create_profile_reindex_search"),
    ]
