# Generated by Django 5.1.1 on 2024-11-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_game_coop_rank"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="server",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("hostname__isnull", True), ("hostname_clean__isnull", True)),
                    models.Q(("hostname__isnull", False), ("hostname_clean__isnull", False)),
                    _connector="OR",
                ),
                name="tracker_server_clean_hostname_null_consistency_check",
            ),
        ),
    ]
