# Generated by Django 4.1.7 on 2023-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0012_profile_alias_updated_at_profile_names_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="search_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
