# Generated by Django 6.0.4 on 2026-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0013_server_tracker_server_clean_hostname_null_consistency_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="slug",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="server",
            name="status_port",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
