apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swat4stats-core.fullname" . }}
  labels:
    {{- include "swat4stats-core.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "staticfiles.conf" }}
  {{ . }}: |-
        {{- $files.Get .  | nindent 6 }}
  {{- end }}
