image:
  repository: ghcr.io/sergeii/swat4stats
  pullPolicy: IfNotPresent
  pullSecrets: ""
  tag: ""

uwsgi:
  port: 9090
  targetPort: 9090
  replicas: 8
  env:
    UWSGI_CHDIR: /app/src
    UWSGI_DISABLE_LOGGING: "true"
    UWSGI_DISABLE_WRITE_EXCEPTION: "true"
    UWSGI_ENABLE_THREADS: "true"
    UWSGI_GID: 10001
    UWSGI_HARAKIRI: 5
    UWSGI_HARAKIRI_VERBOSE: "true"
    UWSGI_HTTP_SOCKET: 0.0.0.0:9090
    UWSGI_LOGGER: "rsyslog:$(SETTINGS_SYSLOG_ADDRESS),app.swat4stats.uwsgi.error"
    UWSGI_IGNORE_SIGPIPE: "true"
    UWSGI_IGNORE_WRITE_ERRORS: "true"
    UWSGI_MASTER: "true"
    UWSGI_MODULE: swat4stats.wsgi
    UWSGI_RELOAD_MERCY: 10
    UWSGI_RELOAD_ON_RSS: 256
    UWSGI_STRICT: "true"
    UWSGI_WORKERS: 1
    UWSGI_UID: 10001
    UWSGI_VIRTUALENV: /app/.venv
    UWSGI_WORKER_RELOAD_MERCY: 10

celery:
  app: swat4stats
  log_level: INFO
  workers:
    - name: default
      replicas: 4
      concurrency: 1
      queues: [default]
      time_limit: 120
      max_tasks: 1000

    - name: sq
      replicas: 2
      concurrency: 1
      queues: [serverquery]
      time_limit: 120
      max_tasks: 1000

    - name: cacheback
      concurrency: 2
      replicas: 1
      queues: [cacheback]
      time_limit: 60
      max_tasks: 10000
  beat:
    replicas: 1

staticfiles:
  port: 10080
  targetPort: 80
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: ""

service:
  name: swat4stats-api
  type: ClusterIP

envFromSecrets: []
## - name: secret-name
##   optional: true

readinessProbe:
  httpGet:
    path: /info/
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com
  periodSeconds: 10
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthcheck/
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com
  periodSeconds: 30
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

sharedEnv:
  SETTINGS_ALLOWED_HOSTS: ".swat4stats.com"
  SETTINGS_LOG_LEVEL: DEBUG
  SETTINGS_EMAIL_BACKEND_ALIAS: smtp
  SETTINGS_SERVER_EMAIL: django@swat4stats.com
  SETTINGS_DEFAULT_FROM_EMAIL: noreply@swat4stats.com
  SETTINGS_SENTRY_API_SAMPLE_RATE: "1.0"
  SETTINGS_SENTRY_CELERY_SAMPLE_RATE: "1.0"
