apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swat4tracker.podname" (set . "Name" "uwsgi") }}
  labels:
    {{- include "swat4tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.uwsgi.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "swat4tracker.selectorLabels" (set $ "Backend" "uwsgi") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swat4tracker.selectorLabels" (set $ "Backend" "uwsgi") | nindent 8 }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ include "swat4tracker.podname" (set . "Name" "copystatic") }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cp", "-r", "/app/static/.", "/var/www/static"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/static
      containers:
        - name: {{ include "swat4tracker.podname" (set . "Name" "sc-staticfiles") }}
          {{- with .Values.staticfiles.image }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - name: static
              containerPort: {{ .Values.staticfiles.port }}
              protocol: TCP
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/static
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: staticfiles.conf
          resources:
            {{- toYaml .Values.staticfiles.resources | nindent 12 }}
        - name: {{ include "swat4tracker.podname" (set . "Name" "uwsgi") }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: uwsgi
              containerPort: {{ .Values.uwsgi.port }}
              protocol: TCP
          env:
          {{- range $key, $val := .Values.uwsgi.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          {{- range $key, $val := .Values.sharedEnv }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          envFrom:
          {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl .name $ }}
                optional: {{ .optional | default false }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.uwsgi.resources | nindent 12 }}
      volumes:
        - name: staticfiles
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "swat4tracker.fullname" . }}
