apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "swat4tracker.fullname" . }}
  labels:
    {{- include "swat4tracker.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host $}}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "swat4tracker.fullname" $ }}
                port:
                  {{- $backend := get $.Values .backend }}
                  {{- $backendPort := get $backend "port" }}
                  number: {{ $backendPort }}
          {{- end }}
  {{- end }}
