image:
  repository: ghcr.io/sergeii/swat4stats.com
  pullPolicy: IfNotPresent
  tag: ""

uwsgi:
  port: 9090
  targetPort: 9090
  workers: 6
  replicas: 4

celery:
  workers:
    - name: default
      replicas: 2
      app: swat4tracker
      args:
        - "--concurrency=1"
        - "--events"
        - "--loglevel=INFO"
        - "--soft-time-limit=100"
        - "--time-limit=120"
        - "--queues=default"
        - "--without-gossip"
        - "--without-mingle"
        - "--without-heartbeat"
    - name: cacheback
      replicas: 2
      app: swat4tracker
      args:
        - "--concurrency=2"
        - "--events"
        - "--loglevel=INFO"
        - "--time-limit=60"
        - "--queues=cacheback"
        - "--without-gossip"
        - "--without-mingle"
        - "--without-heartbeat"
  beat:
    app: swat4tracker
    args:
      - "--loglevel=INFO"

staticfiles:
  port: 10081
  targetPort: 80
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: ""

service:
  type: ClusterIP

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: new.swat4stats.com
      paths:
        - path: /
          pathType: Prefix
          backend: uwsgi
        - path: /errors
          pathType: Prefix
          backend: staticfiles
        - path: /static
          pathType: Prefix
          backend: staticfiles
        - path: /robots.txt
          pathType: Exact
          backend: staticfiles
        - path: /favicon.ico
          pathType: Exact
          backend: staticfiles

envFromSecrets: []
## - name: secret-name
##   optional: true

readinessProbe:
  httpGet:
    path: /
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com

livenessProbe:
  httpGet:
    path: /
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10
