image:
  repository: ghcr.io/sergeii/swat4stats
  pullPolicy: IfNotPresent
  pullSecrets: ""
  tag: ""

uwsgi:
  port: 9090
  targetPort: 9090
  replicas: 8
  terminationGracePeriodSeconds: 10
  env:
    UWSGI_CHDIR: /app/src
    UWSGI_DISABLE_LOGGING: "true"
    UWSGI_DISABLE_WRITE_EXCEPTION: "true"
    UWSGI_ENABLE_THREADS: "true"
    UWSGI_GID: 10001
    UWSGI_HARAKIRI: 5
    UWSGI_HARAKIRI_VERBOSE: "true"
    UWSGI_HTTP_SOCKET: 0.0.0.0:9090
    UWSGI_LOGGER: "rsyslog:$(SETTINGS_SYSLOG_ADDRESS),app.swat4stats.uwsgi.error"
    UWSGI_IGNORE_SIGPIPE: "true"
    UWSGI_IGNORE_WRITE_ERRORS: "true"
    UWSGI_MASTER: "true"
    UWSGI_MODULE: swat4stats.wsgi
    UWSGI_RELOAD_MERCY: 10
    UWSGI_RELOAD_ON_RSS: 256
    UWSGI_STATS: ":1717"
    UWSGI_STATS_HTTP: "true"
    UWSGI_STRICT: "true"
    UWSGI_WORKERS: 1
    UWSGI_UID: 10001
    UWSGI_VIRTUALENV: /app/.venv
    UWSGI_WORKER_RELOAD_MERCY: 10
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

celery:
  app: swat4stats
  logLevel: INFO
  workers:
    - name: default
      replicas: 4
      concurrency: 1
      queues: [default]
      timeLimit: 300
      maxTasks: 1000

    - name: heavy
      replicas: 2
      concurrency: 1
      queues: [heavy]
      timeLimit: 3600
      maxTasks: 100

    - name: sq
      replicas: 2
      concurrency: 1
      queues: [serverquery]
      timeLimit: 120
      maxTasks: 1000

    - name: cacheback
      concurrency: 2
      replicas: 1
      queues: [cacheback]
      timeLimit: 60
      maxTasks: 10000
  beat:
    replicas: 1

uwsgiExporter:
  enabled: true
  port: 9117
  targetPort: 9117
  image:
    repository: timonwong/uwsgi-exporter
    pullPolicy: IfNotPresent
    pullSecrets: ""
    tag: "v1.3.0"
    sha: "7770355b87055b7d6c516a830e5cb1fc2c3e692f265b6d1656df0bccb9456155"

celeryExporter:
  enabled: true
  port: 9808
  targetPort: 9808
  image:
    repository: danihodovic/celery-exporter
    pullPolicy: IfNotPresent
    pullSecrets: ""
    tag: "0.9.2"
    sha: "1afefe83b0e2fd257455d42dfb0c122bd2c4828949e26c2d7cc422d1f42deba0"

staticfiles:
  port: 10080
  targetPort: 80
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: ""
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

service:
  name: swat4stats-core
  type: ClusterIP

envFromSecrets: []
## - name: secret-name
##   optional: true

readinessProbe:
  httpGet:
    path: /info/
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com
  periodSeconds: 10
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthcheck/
    port: uwsgi
    httpHeaders:
      - name: Host
        value: swat4stats.com
  periodSeconds: 30
  initialDelaySeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

sharedEnv:
  SETTINGS_ALLOWED_HOSTS: ".swat4stats.com"
  SETTINGS_LOG_LEVEL: INFO
  SETTINGS_EMAIL_BACKEND_ALIAS: smtp
  SETTINGS_SERVER_EMAIL: django@swat4stats.com
  SETTINGS_DEFAULT_FROM_EMAIL: noreply@swat4stats.com
  SETTINGS_SENTRY_API_SAMPLE_RATE: "0.1"
  SETTINGS_SENTRY_CELERY_SAMPLE_RATE: "0.1"
  SETTINGS_CELERY_BROKER_URL: redis://ha.int.khoroshilov.tech:16379/5
