{{- $appPodName := include "swat4stats.componentName" (dict "name" "uwsgi" "context" $) -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appPodName }}
  labels:
    {{- include "swat4stats.deploymentLabels" (dict "componentName" "uwsgi" "context" $) | nindent 4 }}
spec:
  replicas: {{ .Values.uwsgi.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "swat4stats.selectorLabels" (dict "componentName" "uwsgi" "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swat4stats.deploymentLabels" (dict "componentName" "uwsgi" "context" $) | nindent 8 }}
      annotations:
      {{- if .Values.uwsgiExporter.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.uwsgiExporter.targetPort }}"
      {{- end }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.uwsgi.terminationGracePeriodSeconds }}
      initContainers:
        - name: {{ include "swat4stats.componentName" (dict "name" "copystatic" "context" $) }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cp", "-r", "/app/static/.", "/var/www/static"]
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/static
      containers:
        - name: {{ include "swat4stats.componentName" (dict "name" "staticfiles" "context" $) }}
          {{- with .Values.staticfiles.image }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - name: nginx
              containerPort: {{ .Values.staticfiles.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: staticfiles
              mountPath: /var/www/static
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: staticfiles.conf
          resources:
            {{- toYaml .Values.staticfiles.resources | nindent 12 }}
        {{- if .Values.uwsgiExporter.enabled }}
        - name: {{ include "swat4stats.componentName" (dict "name" "uwsgi-exporter" "context" $) }}
          {{- with .Values.uwsgiExporter.image }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}{{ if .sha }}@sha256:{{ .sha }}{{ end }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - name: exporter
              containerPort: {{ .Values.uwsgiExporter.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: exporter
          resources:
            {{- toYaml .Values.uwsgiExporter.resources | nindent 12 }}
        {{- end }}
        - name: {{ $appPodName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: uwsgi
              containerPort: {{ .Values.uwsgi.targetPort }}
              protocol: TCP
          env:
          {{- range $key, $val := .Values.uwsgi.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          {{- range $key, $val := .Values.sharedEnv }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          envFrom:
          {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl .name $ }}
                optional: {{ .optional | default false }}
          {{- end }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.uwsgi.resources | nindent 12 }}
      volumes:
        - name: staticfiles
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "swat4stats.fullname" (dict "context" $) }}


{{- range .Values.celery.workers }}
{{- $celeryWorkerName := printf "%s-%s-%s" "celery" "worker" .name -}}
{{- $celeryWorkerPodName := include "swat4stats.componentName" (dict "name" $celeryWorkerName "context" $) -}}
{{- $celeryWorkerQueues := join "," .queues -}}
{{- $celeryWorkerCmd := list
    "celery" "-A" $.Values.celery.app "worker"
    "--queues" $celeryWorkerQueues
    "--concurrency" .concurrency
    "--loglevel" $.Values.celery.logLevel
    "--time-limit" .timeLimit
    "--max-tasks-per-child" .maxTasks
    "--events"
    "--pidfile="
}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $celeryWorkerPodName }}
  labels:
    {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryWorkerName "context" $) | nindent 8 }}
spec:
  replicas: {{ .replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "swat4stats.selectorLabels" (dict "componentName" $celeryWorkerName "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryWorkerName "context" $) | nindent 8 }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .timeLimit }}
      containers:
        - name: {{ $celeryWorkerPodName }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            {{- toYaml ($celeryWorkerCmd | toStrings) | nindent 12 }}
          env:
            {{- range $key, $val := $.Values.sharedEnv }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          envFrom:
          {{- range $.Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl .name $ }}
                optional: {{ .optional | default false }}
          {{- end }}
{{ end }}

{{- with .Values.celery }}
{{- $celeryBeatName := printf "%s-%s" "celery" "beat" -}}
{{- $celeryBeatPodName := include "swat4stats.componentName" (dict "name" $celeryBeatName "context" $) -}}
{{- $celeryBeatCmd := list
    "celery" "-A" .app "beat"
    "--loglevel" .logLevel
    "--schedule" "/tmp/celerybeat.db"
    "--pidfile="
-}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $celeryBeatPodName }}
  labels:
    {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryBeatName "context" $) | nindent 8 }}
spec:
  replicas: {{ .beat.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "swat4stats.selectorLabels" (dict "componentName" $celeryBeatName "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryBeatName "context" $) | nindent 8 }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $celeryBeatPodName }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          command:
            {{- toYaml ($celeryBeatCmd | toStrings) | nindent 12 }}
          env:
            {{- range $key, $val := $.Values.sharedEnv }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          envFrom:
          {{- range $.Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl .name $ }}
                optional: {{ .optional | default false }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
{{ end -}}

{{- with .Values.celeryExporter }}
{{- $celeryExporterName := "celery-exporter" -}}
{{- $celeryExporterPodName := include "swat4stats.componentName" (dict "name" $celeryExporterName "context" $) -}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $celeryExporterPodName }}
  labels:
    {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryExporterName "context" $) | nindent 8 }}
spec:
  replicas: {{ if .enabled }}1{{ else }}0{{ end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "swat4stats.selectorLabels" (dict "componentName" $celeryExporterName "context" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "swat4stats.deploymentLabels" (dict "componentName" $celeryExporterName "context" $) | nindent 8 }}
      annotations:
      {{- if .enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .targetPort }}"
      {{- end }}
    spec:
      {{- with $.Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $celeryExporterPodName }}
          image: "{{ .image.repository }}:{{ .image.tag | default "latest" }}{{ if .image.sha }}@sha256:{{ .image.sha }}{{ end }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: CE_BROKER_URL
              value: "{{ $.Values.sharedEnv.SETTINGS_CELERY_BROKER_URL }}"
          ports:
            - name: exporter
              containerPort: {{ .targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: exporter
          resources:
            {{- toYaml .resources | nindent 12 }}
{{ end -}}
