apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "swat4stats.labels" (dict "context" $) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.uwsgi.port }}
      targetPort: {{ .Values.uwsgi.targetPort }}
      protocol: TCP
      name: uwsgi
    - port: {{ .Values.staticfiles.port }}
      targetPort: {{ .Values.staticfiles.targetPort }}
      protocol: TCP
      name: staticfiles
  selector:
    {{- include "swat4stats.selectorLabels" (dict "componentName" "uwsgi" "context" $) | nindent 4 }}
