name: deploy

on:
  workflow_run:
    workflows: [release]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: swat4stats-arc-runner-set
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.jobs.publish.outputs.release_tag != '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install release
        run: >-
          helm upgrade
          --install
          --debug
          --atomic
          --namespace=swat4stats
          --set image.tag=${{ github.event.workflow_run.jobs.publish.outputs.release_tag }}
          --set image.pullSecrets[0].name=swat4stats-registry-creds
          --set envFromSecrets[0].name=swat4stats-secrets
          swat4stats-core
          deployments/charts/swat4stats
        env:
          HELM_KUBEAPISERVER: ${{ secrets.HELM_KUBEAPISERVER }}
          HELM_KUBEINSECURE_SKIP_TLS_VERIFY: 1
          HELM_KUBETOKEN: ${{ secrets.HELM_KUBETOKEN }}
