name: release

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      new_tag: ${{ steps.version.outputs.new_tag }}
      changelog: ${{ steps.version.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump release version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.new_tag != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags for docker image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/sergeii/swat4stats
          tags: |
            type=raw,prefix=,value=${{ needs.build.outputs.new_tag }}
          flavor: |
            latest=true
            prefix=
            suffix=

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfile/prod/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            git_release_ver=${{ needs.build.outputs.new_tag }}
            git_release_sha=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build.outputs.new_tag }}
          name: Release ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}
