name: release

env:
  IMAGE: ghcr.io/sergeii/swat4stats

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      new_tag: ${{ steps.version.outputs.new_tag }}
      changelog: ${{ steps.version.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump release version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

  poetry:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.new_version != ''
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Bump version in pyproject.toml
        run: "poetry version ${{ needs.prepare.outputs.new_version }}"

      - name: Bump version in Chart.yaml
        uses: mikefarah/yq@v4.45.4
        with:
          cmd: >-
            yq -i
            '.appVersion = "${{ needs.prepare.outputs.new_version }}"'
            deployments/charts/swat4stats/Chart.yaml

      - name: Commit changes to pyproject.toml and Chart.yaml
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(poetry): bump version to ${{ needs.prepare.outputs.new_version }}"
          commit_options: "--no-verify --signoff"
          file_pattern: "pyproject.toml deployments/**/Chart.yaml"

  # https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
  build:
    runs-on: ${{ matrix.platform.runner }}
    outputs:
      digest_amd64: ${{ steps.digest.outputs.amd64 }}
      digest_arm64: ${{ steps.digest.outputs.arm64 }}
    strategy:
      matrix:
        platform:
          - id: amd64
            name: linux/amd64
            runner: ubuntu-24.04
          - id: arm64
            name: linux/arm64
            runner: ubuntu-24.04-arm
    needs:
      - prepare
    if: needs.prepare.outputs.new_tag != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare docker meta for platform image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile/prod/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform.name }}
          outputs: type=image,"name=${{ env.IMAGE }}",push-by-digest=true,name-canonical=true,push=true
          build-args: |
            git_release_ver=${{ needs.prepare.outputs.new_tag }}
            git_release_sha=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export image digest
        id: digest
        run: echo "${{ matrix.platform.id }}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image manifest and push
        run: >-
          docker buildx imagetools create
          -t ${{ env.IMAGE }}:latest
          -t ${{ env.IMAGE }}:${{ needs.prepare.outputs.new_tag }}
          ${{ env.IMAGE }}@${{ needs.build.outputs.digest_amd64 }}
          ${{ env.IMAGE }}@${{ needs.build.outputs.digest_arm64 }}

      - name: Inspect manifest
        run: docker buildx imagetools inspect ${{ env.IMAGE }}:latest

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.prepare.outputs.new_tag }}
          name: Release ${{ needs.prepare.outputs.new_tag }}
          body: ${{ needs.prepare.outputs.changelog }}

  deploy:
    runs-on: swat4stats-core-runner
    needs:
      - prepare
      - publish
    if: needs.prepare.outputs.new_tag != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install release
        run: >-
          helm upgrade
          --install
          --debug
          --atomic
          --namespace=swat4stats
          --set image.tag=${{ needs.prepare.outputs.new_tag }}
          --set image.pullSecrets[0].name=swat4stats-registry-creds
          --set envFromSecrets[0].name=swat4stats-secrets
          swat4stats-core
          deployments/charts/swat4stats
        env:
          HELM_KUBEAPISERVER: ${{ secrets.HELM_KUBEAPISERVER }}
          HELM_KUBEINSECURE_SKIP_TLS_VERIFY: 1
          HELM_KUBETOKEN: ${{ secrets.HELM_KUBETOKEN }}
